### ISSUE TITLE
Question page should'nt scroll 

### ISSUE THREAD

**Issue by asweeney16** [Tyson324/mstapp#9]
Please can you make it so that the question page doesn't scroll. Also you have changed the design of the question page but can you make it so that the white bit is in the middle and you can see the photo above and below the white bit.
Thanks :)

**Comment by Tyson324** [comment]
The question page will continue to scroll as this is a responsiveness issue, and of course any responsiveness issues have to be left till last to fix as once they are fixed, any change can break the responsiveness again.
